// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
    guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],

    // ⬇⬇⬇ EZ A FONTOS RÉSZ ⬇⬇⬇
    myApiSidebar: require('./docs/petstore/sidebar.ts').default,
};

module.exports = sidebars;
