// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
    guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
    faqSidebar: [{ type: 'autogenerated', dirName: 'faq' }],
    myApiSidebar: require('./docs/petstore/sidebar.ts').default,
    myOrdersApiSidebar: require('./docs/orders/sidebar.ts').default,
};

module.exports = sidebars;
