openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
  description: Demo service for order management.
servers:
  - url: https://api.example.com
paths:
  /orders:
    get:
      tags: [Orders]
      summary: List orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags: [Orders]
      summary: Create an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /orders/{orderId}:
    get:
      tags: [Orders]
      summary: Get order by ID
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      required: [id, status]
      properties:
        id:
          type: string
          example: "ord_123"
        status:
          type: string
          enum: [pending, paid, shipped, cancelled]
          example: pending
        total:
          type: number
          format: float
          example: 29.99
    CreateOrderRequest:
      type: object
      required: [total]
      properties:
        total:
          type: number
          format: float
          example: 29.99
